#!/usr/bin/env tsx
/**
 * gen-system-prompt.ts — Bake docs/reference/templates/SYSTEM.md into a committed
 * TypeScript module so the agent system prompt has no runtime file dependency.
 *
 * SYSTEM.md stays the human-editable source of the prompt's prose; this script
 * derives `src/agents/system-prompt-source.generated.ts` from it. Embedding
 * (rather than reading SYSTEM.md at runtime) means the prompt resolves
 * identically in dev, npm, bun --compile, and Node SEA binaries, regardless of
 * the working directory or how a deployment stages its files.
 *
 * Run via `pnpm prompt:gen`. `pnpm prompt:check` regenerates and diffs to catch a
 * SYSTEM.md edit that was not re-baked. Wired into `pnpm build` before tsdown.
 */

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(projectRoot, "docs", "reference", "templates", "SYSTEM.md");
const outputPath = path.join(projectRoot, "src", "agents", "system-prompt-source.generated.ts");

function generate() {
  const markdown = fs.readFileSync(sourcePath, "utf-8");
  const body = [
    "// Generated by scripts/gen-system-prompt.ts from docs/reference/templates/SYSTEM.md.",
    "// Do not edit by hand. Edit SYSTEM.md and run `pnpm prompt:gen`.",
    "",
    "/** Raw SYSTEM.md contents, baked in at build time (parsed by system-prompt-sections.ts). */",
    `export const SYSTEM_PROMPT_MARKDOWN = ${JSON.stringify(markdown)};`,
    "",
  ].join("\n");
  fs.writeFileSync(outputPath, body);
  // Canonicalize with oxfmt so the committed artifact matches the format gate and
  // `pnpm prompt:check` stays deterministic.
  const oxfmtBin = path.join(
    projectRoot,
    "node_modules",
    ".bin",
    process.platform === "win32" ? "oxfmt.cmd" : "oxfmt",
  );
  execFileSync(oxfmtBin, ["--write", outputPath], { cwd: projectRoot, stdio: "ignore" });
  console.log(`[gen-system-prompt] Wrote ${path.relative(projectRoot, outputPath)}`);
}

generate();
